### ISSUE TITLE
SIGSEV when joining the network and parsing FJOIN with +f mode

### ISSUE THREAD

**Issue by iwalkalone69** [inspircd/inspircd#1738]
**Description**

SIGSEV when joining the network and parsing FJOIN with +f 3:1

**Steps to reproduce the issue:**

1. Join a server to a network that has a channel with +f mode set

**Describe the results you received:**

Segmentation fault

**Describe the results you expected:**

Join the network without crashing

**Additional information you deem important (e.g. issue happens only occasionally):**

Tue Dec 03 2019 06:01:59 m_spanningtree: S[11] I :888 FJOIN #malaga 915277770 +CTfnrtu 3:1 :,396AAAAKF:266 ,445AACZYF:431497 ,695AAK78A:106523 ,048AALKP1:107287 ,898AACZYR:433318 ,898AACZZC:433354 ,747AAJTCH:106433 o,747AALK69:109042 ,695AALJJX:107653 ,445AACZWD:431530 v,396AAJRY8:107810 ,434AAJS1T:103732 ,396AALGTU:109899 ,445AACYTP:426266 ,396AALJV6:110402 ,048AALI9P:107110 ,695AAJRRS:104792 ,048AALI7X:107128 ,747AAKBKU:107393 ,434AAJTGV:103922 ,445AACZ2Y:432178 ,898AACY3M:429273 ,445AACYOA:425553 ,445AACZS0:430798 ,396AALHJ4:110040

Thread 1 "inspircd" received signal SIGSEGV, Segmentation fault.
ParamMode<MsgFlood, SimpleExtItem<floodsettings, stdalgo::defaultdeleter<floodsettings> > >::GetParameter () at include/parammode.h:73
73                      mh->SerializeParam(chan, ext.get(chan), out);
(gdb) bt
#0  ParamMode<MsgFlood, SimpleExtItem<floodsettings, stdalgo::defaultdeleter<floodsettings> > >::GetParameter () at include/parammode.h:73
#1  0x00005555555c5bf5 in Channel::GetModeParameter[abi:cxx11](ModeHandler*) () at include/channels.h:308
#2  ShouldApplyMergedMode () at /srv/ChatHispanoEngine/releases/20191107053948/apps/InspIRCd/src/mode.cpp:415
#3  ModeParser::ProcessSingle () at /srv/ChatHispanoEngine/releases/20191107053948/apps/InspIRCd/src/mode.cpp:460
#4  0x00005555555c5dd6 in ModeParser::Process () at /srv/ChatHispanoEngine/releases/20191107053948/apps/InspIRCd/src/mode.cpp:426
#5  0x00007ffff61c5c64 in CommandFJoin::Handle () at /srv/ChatHispanoEngine/releases/20191107053948/apps/InspIRCd/src/modules/m_spanningtree/fjoin.cpp:172
#6  0x00007ffff61f0b52 in TreeSocket::ProcessConnectedLine () at /srv/ChatHispanoEngine/releases/20191107053948/apps/InspIRCd/src/modules/m_spanningtree/treesocket2.cpp:388
#7  0x00007ffff61f16f5 in TreeSocket::ProcessLine () at /srv/ChatHispanoEngine/releases/20191107053948/apps/InspIRCd/src/modules/m_spanningtree/treesocket2.cpp:219
#8  0x00007ffff61ee352 in TreeSocket::OnDataReady () at /srv/ChatHispanoEngine/releases/20191107053948/apps/InspIRCd/src/modules/m_spanningtree/treesocket1.cpp:214
#9  0x00005555555b9da6 in StreamSocket::DoRead () at /srv/ChatHispanoEngine/releases/20191107053948/apps/InspIRCd/src/inspsocket.cpp:173
#10 StreamSocket::DoRead () at /srv/ChatHispanoEngine/releases/20191107053948/apps/InspIRCd/src/inspsocket.cpp:161
#11 0x00005555555b9e36 in StreamSocket::OnEventHandlerRead () at /srv/ChatHispanoEngine/releases/20191107053948/apps/InspIRCd/src/inspsocket.cpp:470
#12 0x00005555555e676d in SocketEngine::DispatchTrialWrites () at /srv/ChatHispanoEngine/releases/20191107053948/apps/InspIRCd/src/socketengine.cpp:135
#13 0x00005555555b3048 in InspIRCd::Run () at /srv/ChatHispanoEngine/releases/20191107053948/apps/InspIRCd/src/inspircd.cpp:667
#14 0x0000555555584ee2 in main () at /srv/ChatHispanoEngine/releases/20191107053948/apps/InspIRCd/src/inspircd.cpp:698

**Output of `./bin/inspircd --version`:**

InspIRCd version: 3.4.0-de72e6453

**Comment by iwalkalone69** [comment]
Sorry, I was testing with wrong branch.

Can't reproduce with insp3 branch, so I close it.
